insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (1, 'Softley', 'Clerkclaude', '200-98-5238', 'M', 'Alegria', true,false,'16');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (2, 'Treswell', 'Latisha', '893-58-6795', 'F', 'Qiryat Motzkin', false, false,'24');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (3, 'Holley', 'Vassili', '339-52-5576', 'M', 'No Kunda', false, false,'46');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (4, 'Miners', 'Benedick', '432-38-7827', 'M', 'Río Pico', false, true,'52');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (5, 'Hatfull', 'Bondie', '632-34-8578', 'M', 'Laocheng', true, true,'12');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (6, 'Benettini', 'Phillida', '701-53-8863', 'F', 'Du’ermenqin', true, false,'32');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (7, 'Nanninini', 'Feliks', '416-61-7386', 'M', 'Şafwá', true, true,'46');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (8, 'Coull', 'Em', '770-90-6970', 'F', 'Tosno', true, true,'86');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (9, 'Childs', 'Mellie', '577-63-1663', 'F', 'Ayo', true, true,'11');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (10, 'Jorio', 'Dewey', '770-50-1051', 'M', 'Fayzabad', true, false,'3');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (11, 'Lippi', 'Doug', '807-09-2256', 'M', 'Shenjing', true, false,'78');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (12, 'Milley', 'Charin', '312-07-1803', 'F', 'Zbiroh', false, true,'89');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (13, 'Mantripp', 'Matthias', '253-41-9287', 'M', 'Myronivka', false, false,'64');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (14, 'Forker', 'Verla', '846-71-0138', 'F', 'Fort Liberté', false, true,'28');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (15, 'Kensitt', 'Kay', '824-38-0281', 'F', 'Jinqu', false, false,'82');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (16, 'Whorf', 'Garnette', '293-18-0317', 'F', 'Merida', true, true,'35');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (17, 'Pinar', 'Myrtice', '557-26-5945', 'F', 'Tarnawatka', false, false,'29');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (18, 'Syred', 'Beniamino', '467-08-9351', 'M', 'Cigedang', false, false,'56');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (19, 'Cordoba', 'Ermina', '702-30-4243', 'F', 'Uptar', true, true,'76');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (20, 'Float', 'Alexei', '727-94-6405', 'M', 'Balazar',true, false, '83');
insert into Citoyen (id_Citoyen, nom, prenom, num_Assurance_Social, sexe, Ville, is_Tested, is_Vaccinated, age) values (21, 'Munger', 'Jeremie', '123', 'H', 'Saint-philippe', true, true,'20');
